### ISSUE TITLE
Jira plugin send api didn't  have an authorization

### ISSUE THREAD

**Issue by dongyan8912** [RoadieHQ/backstage-plugin-jira#102]
when I use jira plugin to get the jira data. I set my authorization in app-config.yaml like this:

 '/jira/api':
    target: https://jira.huami.com
    allowedHeaders: ['Authorization']
    headers:
      Authorization: 'Basic    {api_token}'
      Accept: 'application/json'
      Content-Type: 'application/json'
      X-Atlassian-Token: 'nocheck'
      User-Agent: "MY-UA-STRING"

But  when I check the api,there is no authorization .

curl 'http://localhost:7000/api/proxy/jira/api/rest/api/latest/search' \
  -H 'Connection: keep-alive' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'Accept: */*' \
  -H 'Origin: http://localhost:3000' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:3000/' \
  -H 'Accept-Language: en,zh-CN;q=0.9,zh;q=0.8' \
  --data-raw '{"jql":"project = \"CLOUD\"\n      AND issuetype = \"新功能\"\n      \n      \n      AND statuscategory not in (\"Done\")\n    ","maxResults":0}' \
  --compressed

**Comment by dongyan8912** [comment]
now  I map the issuetype to  English type，the question is resolved

**Comment by Irma12** [comment]
@dongyan8912 Glad it is solved and hope you won't experience any more problems :)
