### ISSUE TITLE
Suggestion: Don't show the empty issue categories

### ISSUE THREAD

**Issue by O5ten** [RoadieHQ/backstage-plugin-jira#21]
As you can see it doesn't look great when having multiple issue categories, which isn't uncommon. 
Either make it look better or hide the categories that lack issues entirely. Perhaps even make it configurable which ones to show. 

![image](https://user-images.githubusercontent.com/3242379/101351212-8acbf300-3890-11eb-8458-20048c41ec40.png)

**Comment by O5ten** [comment]
And before you ask why we have this many unused issue categories. Management wanted it that way.

**Comment by mcalus3** [comment]
I can't come up with any reason for the user to have categories with 0 issues visible. I think that the most simple solution to this is to not display categories with 0 issues (by deafult) and have a toggle for user to enable it (if someone would occasionally want to peek what different categories are there).

**Comment by adamdmharvey** [comment]
While I agree conceptually this would make sense and visually be more clear, I can see my colleagues having the opposite question: "Hey, you forgot tests in the report - it only shows stories, bugs, and tasks."  But we don't know if there ARE no tests.  Lack of data presentation is _different_ than confirmation of empty data?  I would think in fact to management it would be useful to know this component, in fact, lacks tests, which would mean it may lack quality.  Thoughts?

**Comment by mcalus3** [comment]
Technically speaking, I could add an expanding panel with some label like "show empty issue types", but I wanted to maintain as much visual simplicity as i could - in the end it's an overview widget and it shouldn't be used to generate reports, rather get the most valuable piece of the info.

I've implemented showing non-empty ones by default and an ability to switch it by the user to "all". The setting will be stored in local storage so it wouldn't be necessary to toggle it every time user opens the browser.

https://www.loom.com/share/d652cf4430f840e3b78a8153676ea342 - @O5ten, feel free to comment if it fits your use case well :)

**Comment by O5ten** [comment]
@mcalus3 Fits my usecase perfectly. :)
