### ISSUE TITLE
My Stories 

### ISSUE THREAD

**Issue by regicsolutions** [RoadieHQ/backstage-plugin-jira#26]
## Feature Suggestion
Be able to see “My Stories” in backstage, maybe in the org plugin view where you can see all stories an engineer and there team are working on vs going to Jira. I got the idea from this project - https://github.com/johannesjo/super-productivity

Demo: https://app.super-productivity.com/#/tag/TODAY/tasks

**Comment by adamdmharvey** [comment]
It's almost like what might be missing is a landing page in Backstage, where it's just the catalog today, and that landing page could have a widget for "your work".  That then is something that is extensivble, like by this plugin, to connect Jira to it, but then other plugins could also extend it and sort of all "feed in" the work to the TO DO list.

Conceptually, I love it!  Think maybe the plumbing in Backstage itself isn't there yet for this plugin to yet trigger upon it, but once it is might be an easy one?  (there are built in filters to get "my assigned work")

**Comment by regicsolutions** [comment]
Yep, I agree we need an overview page. How can we get Spotify to open source this plugin? Lol 

![image](https://user-images.githubusercontent.com/6157895/103838070-1c7a7c00-505a-11eb-93ab-9fb3ed045c48.jpeg)

**Comment by dtuite** [comment]
@regicsolutions agree that this would be amazing. However, this is a feature request for `backstage/backstage` rather than this plugin so I will close this.
