### ISSUE TITLE
User-Agent: "MY-UA-STRING"

### ISSUE THREAD

**Issue by regicsolutions** [RoadieHQ/backstage-plugin-jira#29]
Is the User-Agent string required for Jira Server? If so, is there any documentation on how to obtain the string? 

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- Plugin Version (version of this software e.g. v0.4.3):
- Backstage version (e.g. 0.1.1-alpha23):
- NodeJS Version (e.g. v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information (e.g. chrome 85):

**Comment by mcalus3** [comment]
`User-Agent` header is added to the requests to prevent some sort of bugs, but it's irrelevant for us what's being sent there, so you can leave it just as in the readme.
