### ISSUE TITLE
Plugin unable to authenticate to Jira Server

### ISSUE THREAD

**Issue by martina-if** [RoadieHQ/backstage-plugin-jira#30]
A user in Discord reported that the plugin isn't working for him with Jira Server.

> we are not using Jira cloud, we use Jira Server which i think the api url may be different (similar to the differences between Bitbucket Server and Bitbucket Cloud) we use an id to login, not email but i tried base 64 encoding both (user name and email) and my API token isnt even being hit, it does allow me to register the API with the jira project key annotation but i dont see anything in the about card...
>
> i got it hitting jira now using my username vs email but getting an error 'Request failed with status code 403' here are the logs, any ideas?
```
'/jira/api':
    target: https://jiraserver.com
    headers:
      Authorization: Basic MYTOKENUSINGUSERNAME
      Accept: application/json
      Content-Type: application/json
      X-Atlassian-Token: no-check
[12:53 AM]
"GET /api/proxy/jira/api/rest/api/latest/project/PIL1 HTTP/1.1" 200 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" type=incomingRequest
"POST /api/proxy/jira/api/rest/api/latest/search HTTP/1.1" 403 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" type=incomingRequest
"POST /api/proxy/jira/api/rest/api/latest/search HTTP/1.1" 403 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" type=incomingRequest
"POST /api/proxy/jira/api/rest/api/latest/search HTTP/1.1" 403 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 
```

**Comment by mcalus3** [comment]
This might be connected to the https://github.com/RoadieHQ/backstage-plugin-jira/issues/29 as I don't see User-Agent header in there. Try adding it to the config (just like in the guide in the Readme) - it's not relevant what value this header has, it just has to be present in the request.

**Comment by regicsolutions** [comment]
> This might be connected to the #29 as I don't see User-Agent header in there. Try adding it to the config (just like in the guide in the Readme) - it's not relevant what value this header has, it just has to be present in the request.

Spot on @mcalus3 worked like a charm. @martina-if Thanks for the help!

**Comment by regicsolutions** [comment]
Any reason why i am not seeing the activity stream shown in the readme? i tried with and without a component annotation with the same result.

![image](https://user-images.githubusercontent.com/6157895/104853850-818f6680-58d1-11eb-9d63-ba599d4d1a4f.png)

**Comment by mcalus3** [comment]
I don't know if I can fix this in the code, i don't have any idea for this.
