### ISSUE TITLE
Jira Card breaks if activity stream contains content with < or > that is not an HTML element

### ISSUE THREAD

**Issue by adamdmharvey** [RoadieHQ/backstage-plugin-jira#57]
## Expected Behavior

The activity stream displays.

## Current Behavior

For one of my projects, I discovered the Jira Card was broken. I tried to troubleshoot it, and best I can tell, it breaks anytime someone adds a comment to a Jira story where the CONTENT of their comment contains the `<` or `>` character.

In particular, I have a few people who have pasted in e-mail forwards and the output of a single `entry.content` looks roughly like so:

```
<blockquote>    <p><b>From:</b> Last, First <last.first@company.net> <br>  <b>Sent:</b> Wednesday, February 17, 2021 11:09 PM<br>  <b>To:</b> Last, First <username@company.com>; Last, First <lfirst@domain.com><br>  <b>Subject:</b> RE: Title of E-mail - <a class="issue-link" href="https://jiraurl.com/browse/PROJECTKEY-123" title="Jira Story Title">PROJECTKEY-123</a> - more of a sentence</p>
</blockquote>
```

This seems to break the entire card.

## Possible Solution

Parse function may need to handle the output in a different way? I don't know if it's coming that way from an HTMl scrape or what, but it seems to be getting confused thinking `<first.last@domain.com>` is an HTML field and bombing out.

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Context

Specifically seems to break on this line, which if I comment it out, the rest of the card displays:

https://github.com/RoadieHQ/backstage-plugin-jira/blob/5f6fd526f46c66bdff2c046deba588e983aa4f68/src/components/JiraCard/components/ActivityStream.tsx#L142-L144
Unable to display this entity's Jira project, seemingly at all. (This team seems to frequently paste e-mails into comments!)

## Your Environment

- Plugin Version (version of this software e.g. v0.4.3):
- Backstage version (e.g. 0.1.1-alpha23):
- NodeJS Version (e.g. v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information (e.g. chrome 85):

**Comment by ayshiff** [comment]
Thanks @adamdmharvey 👍

I looked at the issues of `html-react-parser` and it turns out that one person asked the same question: see [here](https://github.com/remarkablemark/html-react-parser/issues/124).

As indicated in the reply, I think the simplest method would be to use an HTML sanitization library like `sanitize-html`.

This would allow us to sanitize our HTML content by specifying the allowed tags.
It could also save us from having similar problems with other tags in the future.

```js
const clean = sanitizeHtml(dirty, {
  allowedTags: [ 'b', 'i', 'em', 'strong', 'a' ],
});
```
