### ISSUE TITLE
Allow the Card to be configurable with a default filter

### ISSUE THREAD

**Issue by iain-b** [RoadieHQ/backstage-plugin-jira#58]
Following on from @adamdmharvey 's suggestion on discord.

https://discord.com/channels/760879902391009330/760879902391009333/812215403572494377

## Feature Suggestion

Currently we render a summary of _all_ issues in a jira project but allow filtering by status. We should allow a default filter option and we should set this to open by default.

**Comment by adamdmharvey** [comment]
When defining statuses in Jira, it allows you to categorize them.  I believe these categories are built in, and thus there may be way to show all "open" or "in progress" statuses in a project vs. all which might be "done".

![image](https://user-images.githubusercontent.com/33203301/108542266-89b43a80-72b1-11eb-93ef-621438156aee.png)

e.g., some of my teams will be running scrum and some Kanban, and there are a lot of customizations across the firm. So some teams may have a CLOSED while some have a DONE status, but that's both in the end, meaning a _finished piece of work_ which should not be in count on the "default" card I think.

**Comment by padraigobrien** [comment]
I am closing this issue now. if you have any further problems feel free to log another issue or join us on our discord server, https://discord.gg/chuePWkM
