### ISSUE TITLE
Activity Stream should be for a project and not an entire instance

### ISSUE THREAD

**Issue by adamdmharvey** [RoadieHQ/backstage-plugin-jira#6]
The activity stream currently displayed seems to be from the entire Jira instance.  My instance has over 1.4 million issues and over 6000 projects, and I personally have read access to hundreds of projects with my user I used a token for.  Thus when displaying the card, the activity stream I see is not really relevant to the component I'm viewing.

Suggest replacing it with the activity stream of the given project as defined in the annotation (e.g., `jira/project-key`).

**Comment by adamdmharvey** [comment]
If I'm not mistaken, you're using the RSS feed?

It looks like on my project homepage, the only nuance is to add `steams=key+IS+projectKey` to the calling url?  I may play around with it on my side and if I can, will submit a PR.

**Comment by adamdmharvey** [comment]
In testing, looks like components csn also be passed as well:

```
https://mycorporate.jiraurl.com/activity?maxResults=10&streams=key+IS+PROJKEY+and+component+IS+%22My+Component%22&providers=thirdparty+dvcs-streams-provider+issues&title=undefined
```

**Comment by lewtakm** [comment]
@adamdmharvey yes I am using RRS feed to get Activity Stream. 
I create a PR (https://github.com/RoadieHQ/backstage-plugin-jira/pull/13) that adds projectKey variable to Activity Stream request but I am not able to make component filter works. Where did you find this solution? 

On my Jira setting page I have only this options:
![chrome_mrN97R4Lno](https://user-images.githubusercontent.com/36006588/100600872-29d97380-3302-11eb-9251-bb827de7166f.png)

Maybe you got some additional plugins installed into your Jira instance?

**Comment by adamdmharvey** [comment]
@lewtakm No, URL hack. 😉 In fact, the screen you show above is not available in the Jira Data Center product that I've ever seen. How did you get there?
