### ISSUE TITLE
Component filter not applying to stream

### ISSUE THREAD

**Issue by athal7** [RoadieHQ/backstage-plugin-jira#61]
## Expected Behavior

Activity stream filters by the specified component

## Current Behavior

Activity stream has all activity for the project

**Comment by padraigobrien** [comment]
Hi @athal7 , thanks for logging this, I will take a look and get back to you

**Comment by Irma12** [comment]
Hello @athal7 thank you for reporting this, we have investigated possible solutions and unfortunately filtering activity stream by component is not supported at the moment(https://support.atlassian.com/confluence-cloud/docs/add-the-activity-stream-gadget/) so we won't be introducing that improvement now. However, we will certainly try to find some workaround in some of the future iterations :)

**Comment by athal7** [comment]
Thanks @Irma12
