### ISSUE TITLE
UI overlapping text issue

### ISSUE THREAD

**Issue by dtuite** [RoadieHQ/backstage-plugin-jira#65]
Reported on discord: https://discord.com/channels/760879902391009330/760879902391009333/816864094731894806

The "New Feature" text is overlapping.

![Screen_Shot_2021-03-03_at_6 46 28_PM](https://user-images.githubusercontent.com/562403/109972684-824c5280-7cef-11eb-85a6-aabc7fc473d7.png)

**Comment by Xantier** [comment]
Closed with `Fix styling on status text #69`
