### ISSUE TITLE
Returned statuses should be project specific and not instance wide

### ISSUE THREAD

**Issue by adamdmharvey** [RoadieHQ/backstage-plugin-jira#8]
When I first clicked on the status filter button, it delayed a good 4-5 seconds before painting. Looking into it, it seems it's the REST API endpoint for all statuses on a given Jira instance:

https://github.com/RoadieHQ/backstage-plugin-jira/blob/c1314df6131fab02c534433b8899df67469892a8/src/api/index.ts#L133

My instance has hundreds of customized statuses, where some teams do agile, some issue tracking, some basic Kanban, etc, and each project uses a set of customized statues based on predefined patterns. So my given project does not uses most of the returned list of statuses.

Since this widget displays data specific for a project, I think the status collection should be only those valid for the project. The project status call on large instances is also faster.

I tried a PR to fix this, but I'll admit to getting a bit lost into the mechanics of React's useState calls firing the hooks.

But the simple API change is as so:

```
const request = await axios.get(`${apiUrl}project/${projectKey}/statuses`);
```

It returns in the same format as the root instance `/status` API call.  Essentially, need to call the statuses call per project like so:

https://docs.atlassian.com/software/jira/docs/api/REST/8.14.0/#api/2/project-getAllStatuses

And this necessitates passing the projectKey into the status hook.

**Comment by lewtakm** [comment]
Hi @adamdmharvey,
thank you for a report. I just made a PR that should resolve this issue. I also merged all of yours PR, new version of the plugin with yours and mine changes should be published on the NPM tomorrow 👍

**Comment by adamdmharvey** [comment]
Thanks so much @lewtakm !!

**Comment by adamdmharvey** [comment]
Tested out 0.2.1 and it works great it's also sooooooooo much faster for me.  thanks all ! 🎉 🎉 🎉
