### ISSUE TITLE
Project avatars not reachable to Jira Data Center Instance

### ISSUE THREAD

**Issue by adamdmharvey** [RoadieHQ/backstage-plugin-jira#9]
My project avatar us issuing an HTTP 403 unauthorized and not displaying in the widget:

![image](https://user-images.githubusercontent.com/33203301/100532817-2e4f4080-31cb-11eb-842b-750dfa35faf3.png)

![image](https://user-images.githubusercontent.com/33203301/100532839-7d957100-31cb-11eb-8eac-be6590e2114f.png)

It's funny because if I grab the URL and fire it in my browser, I'm already authenticated to the instance and it shows me immediately.  So doesn't seem to be a CORS/Backstage proxy issue, but not sure why.

**Comment by adamdmharvey** [comment]
So I can't quite explain this, other than maybe browser caching (since I was surfing Jira separate from my Backstage testing), but icons are showing up for me now, which let me fire a separate PR to enlarge the icon. (https://github.com/RoadieHQ/backstage-plugin-jira/pull/10)

Would still like to keep this open as it may be a timing issue, and I'll keep doing testing to report back, but an oddity for sure and you can see it in my screen caps above.

**Comment by lewtakm** [comment]
@adamdmharvey did you noticed this problem again in the past two days?
