### ISSUE TITLE
Issues when upgrade to Backstage release-2021-05-27

### ISSUE THREAD

**Issue by axdotl** [RoadieHQ/backstage-plugin-jira#95]
## Expected Behavior

When upgrade to [latest Backstage release](https://github.com/backstage/backstage/releases/tag/release-2021-05-27) no issues should occur.

- Upgrade done via `yarn backstage-cli versions:bump`
- Plugin version: `@roadiehq/backstage-plugin-jira": "^1.0.6`

## Current Behavior

`<EntitySwitch.Case if={isJiraAvailable}>` results in following error:

```
Type '(entity: import("/node_modules/@roadiehq/backstage-plugin-jira/node_modules/@backstage/catalog-model/dist/index").Entity) => boolean' is not assignable to type '(entity: import("/node_modules/@backstage/catalog-model/dist/index").Entity) => boolean'.
  Types of parameters 'entity' and 'entity' are incompatible.
    Type 'import("/node_modules/@backstage/catalog-model/dist/index").Entity' is not assignable to type 'import("/node_modules/@roadiehq/backstage-plugin-jira/node_modules/@backstage/catalog-model/dist/index").Entity'.
```

This snippet
```
<Grid item md={6}>
  <EntityJiraOverviewCard/>
</Grid>
```

results in following runtime error:

```
Uncaught TypeError: Cannot read property 'metadata' of undefined
    at useProjectEntity (index.esm.js?b6ad:285)
    at JiraCard (index.esm.js?b6ad:530)

The above error occurred in the <JiraCard> component:
    in JiraCard (created by Extension(Component))
```

## Possible Solution

I assume it can be fixed by update dependencies in `package.json`

```sh
$ yarn backstage-cli versions:check --fix
The following packages must be deduplicated by updating dependencies in package.json

  @backstage/plugin-catalog-react @ ^0.1.6 should be changed to ^0.2.0

The following packages can be deduplicated by updating dependencies in package.json

  @backstage/catalog-model @ ^0.7.10 should be changed to ^0.8.0
  @backstage/catalog-model @ ^0.7.9 should be changed to ^0.8.0
```

## Steps to Reproduce

see above

## Context

upgrade Backstage

## Your Environment

- Plugin Version (version of this software e.g. v0.4.3): 1.0.6
- Backstage version (e.g. 0.1.1-alpha23): [release-2021-05-20](https://github.com/backstage/backstage/releases/tag/release-2021-05-20)
- NodeJS Version (e.g. v12): v12.19.0
- Operating System and Version (e.g. Ubuntu 14.04): `Pop!_OS 20.10`
- Browser Information (e.g. chrome 85): Opera 76.0.4017.123

**Comment by Irma12** [comment]
Hey @axdotl thank you for reporting this issue, we will try reproducing it and fix as soon as possible.

**Comment by Irma12** [comment]
@axdotl We have updated to the corresponding packages, thank you for reporting the issue and suggesting the solution. Check out new version (v.1.0.7), it should work now :)

**Comment by Irma12** [comment]
@axdotl We have updated to the corresponding packages, thank you for reporting the issue and suggesting the solution. Check out new version (v.1.0.7), it should work now :)
